In [1]:
#Access 1-D Elements
import numpy as np
i = np.array([10, 20, 30, 40, 50])
print(i.shape)

(5,)


In [3]:
#Access 2-D Elements
import numpy as np
i = np.array([[10, 20, 30, 40, 50], 
              [60,70,80,90,100]])
print(i.shape)

(2, 5)


In [4]:
#Access 3-D Elements
import numpy as np
i = np.array([
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]],
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]]
])
print(i.shape)

(2, 3, 5)


In [5]:
#NumPy Reshaping Data 1-D to 2-D
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
j = i.reshape(5,2)
j

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [6]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])
j = i.reshape(4,3)
j

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [7]:
#NumPy Reshaping Data 1-D to 3-D
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 
130, 140,150, 160])
j = i.reshape(2,2,4)
j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [8]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 
130, 140,150, 160])
j = i.reshape(2,4,2)
j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [10]:
#UNKNOWN DIMENSION
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 
130, 140,150,160])
j = i.reshape(2,4,-1)
j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [11]:
#MULTIDIMENSIONAL INTO 1D
import numpy as np
i = np.array([
[[10, 20, 30], [40, 50, 60]],
[[70, 80, 90], [100, 110, 120]], 
[[130, 140,150],[1,2,3]]
])
j = i.reshape(-1)
j

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150,   1,   2,   3])

In [12]:
import numpy as np
i = np.array([[10, 20, 30], [40, 50, 60],[70,80,90]])
j = i.reshape(-1)
j

array([10, 20, 30, 40, 50, 60, 70, 80, 90])